// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw2VmK2qfW62nS33944IrPztZog1fXgtU',
    appId: '1:177663459380:web:d075a72e3ff01911070a61',
    messagingSenderId: '177663459380',
    projectId: 'social-media-app-cb9a1',
    authDomain: 'social-media-app-cb9a1.firebaseapp.com',
    storageBucket: 'social-media-app-cb9a1.appspot.com',
    measurementId: 'G-X7DG2VXFX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz_cT2WU6qVHusVtAbWvEQqzUMYaqaLkw',
    appId: '1:177663459380:android:c64ea46169e476a6070a61',
    messagingSenderId: '177663459380',
    projectId: 'social-media-app-cb9a1',
    storageBucket: 'social-media-app-cb9a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Tvh_72dnC5hKf4daE3Bt0U7QVj-lRbY',
    appId: '1:177663459380:ios:4d377ace98a379aa070a61',
    messagingSenderId: '177663459380',
    projectId: 'social-media-app-cb9a1',
    storageBucket: 'social-media-app-cb9a1.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1Tvh_72dnC5hKf4daE3Bt0U7QVj-lRbY',
    appId: '1:177663459380:ios:c6a671efd743b70c070a61',
    messagingSenderId: '177663459380',
    projectId: 'social-media-app-cb9a1',
    storageBucket: 'social-media-app-cb9a1.appspot.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
